services:
  seq:
    image: datalust/seq:latest
    container_name: tt-backend-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
      - SEQ_API_CANONICALURI=http://localhost:8081
    ports:
      - "8081:80"
      - "5341:5341" 
    volumes:
      - seq_data:/data
    restart: unless-stopped

  postgres_db:
    image: postgres:16-alpine
    container_name: tt-backend-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tt-backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  seq_data: 
  postgres_data: