// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI.DataStorage.Postgres;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinimalAPI.DataStorage.Postgres.Migrations
{
    [DbContext(typeof(PostgresReportDbContext))]
    partial class PostgresReportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI.Domain.StatQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("queries", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.StatQueryResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountSignIn")
                        .HasColumnType("integer");

                    b.Property<Guid>("StatQueryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatQueryId")
                        .IsUnique();

                    b.ToTable("query_results", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.StatQueryResult", b =>
                {
                    b.HasOne("MinimalAPI.Domain.StatQuery", null)
                        .WithOne()
                        .HasForeignKey("MinimalAPI.Domain.StatQueryResult", "StatQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
